### ISSUE TITLE
Switch to GithubAction for CI

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1572]
Here is all the capabilities we have in CircleCI that would (?) need to be transferred to GithubAction:
- [x] changelog/news checker (#1571)
- [x] build / nosetest / unit test (#1569)
- [x] build cyclus/cyclus:latest docker image (on merge) (#1570 WIP)
- [ ] build cyclus/cyclis:stable docker image (on release) (#1570 WIP) 
- [ ] generate `.deb` package (on release) 
- [ ] trigger cycles-suite test (to ensure `cycamore` and `cymetric` are not broken by the latest changes)

I'll edit this list with the corresponding PR number

**Comment by gonuke** [comment]
A github action for release was added in #1597. It doesn't do all of these things yet, but we can discuss how they fit in our new strategy.

**Comment by gonuke** [comment]
Let's close this in favor of the [project](https://github.com/orgs/cyclus/projects/4/views/1)
