### ISSUE TITLE
Moving to GCSG Compliance

### ISSUE THREAD

**Issue by scopatz** [cyclus/cyclus#544]
This is an organizational issue to move us into compliance with the [Google C++ Style Guide](http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml).  We will be focusing on API elements over implementation.  Rather than spread this out over the next couple of months, at last weeks developer call, we decided to tackle this head on in the next couple of weeks.  Expect merge conflicts and CI breakages galore!
- [x] namespace names: @scopatz #531 #545
- [x] exceptions: @rwcarlsen #537 
- [x] file names: @gidden 
- [x] function names: @rwcarlsen #554 
- [x] enum names @rwcarlsen 
- [x] type names: classes are correct, others may not be @rwcarlsen #552
- [x] macro names @rwcarlsen 
- [x] indentation @scopatz #530

*\* comment style consistency (within each file) - see https://github.com/cyclus/cyclus/issues/553

Please adjust the above list as you claim, open PRs, and finish these tasks.  Feel free to clean up other issues as well when you are in these files.  After this issue is closed we will move on to doing something similar for cycamore.
